# Generated by Django 2.0.7 on 2018-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_extract_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('COMPLETED', 'completed')], default='CREATED', max_length=32)),
            ],
        ),
    ]
