# Generated by Django 2.0.7 on 2018-07-24 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_extract_app', '0003_auto_20180715_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Config JSON')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='annotated_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Annotated JSON'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='OCR JSON'),
        ),
    ]
