# Generated by Django 2.0.7 on 2018-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_extract_app', '0004_auto_20180724_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionmodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('Search And Layout', 'SEARCH_AND_LAYOUT'), ('Zonal', 'ZONAL')], default=None, max_length=100, verbose_name='Model Type'),
        ),
    ]
