# Generated by Django 2.0.7 on 2018-07-22 12:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_extract_app', '0005_auto_20180722_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Config JSON')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='Tags')),
            ],
        ),
    ]
