# Generated by Django 2.0.7 on 2018-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_extract_app', '0002_extractrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extract_request',
            field=models.ForeignKey(blank=True, default=None, on_delete='CASCADE', to='document_extract_app.ExtractRequest', verbose_name='ExtractRequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_output',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='OCR Output'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('PROCESSED', 'processed')], default='CREATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='File'),
        ),
    ]
